### ISSUE TITLE
[Bug] Validation Error on Rule Upload of Upstream Rule

### ISSUE THREAD

**Issue by operatorequals** [elastic/detection-rules#1445]
**Describe the bug**
When using `detection_rules` CLI to upload rules to my Kibana (7.12.1) instance (self-hosted through ECK), it is impossible to make some stock rules work. Specifically the error pasted in *screenshots* part is shown.

**To Reproduce**
1. Run `python -m detection_rules kibana upload-rule --directory rules/promotions` 
See error

**Expected behavior**
The expected behaviour is to upload the rules to Kibana Detections App and get the below output:
```
█▀▀▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄   ▄      █▀▀▄ ▄  ▄ ▄   ▄▄▄ ▄▄▄
█  █ █▄▄  █  █▄▄ █    █   █  █ █ █▀▄ █      █▄▄▀ █  █ █   █▄▄ █▄▄
█▄▄▀ █▄▄  █  █▄▄ █▄▄  █  ▄█▄ █▄█ █ ▀▄█      █ ▀▄ █▄▄█ █▄▄ █▄▄ ▄▄█

Successfully uploaded X rules
```

**Screenshots**
```
█▀▀▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄   ▄      █▀▀▄ ▄  ▄ ▄   ▄▄▄ ▄▄▄
█  █ █▄▄  █  █▄▄ █    █   █  █ █ █▀▄ █      █▄▄▀ █  █ █   █▄▄ █▄▄
█▄▄▀ █▄▄  █  █▄▄ █▄▄  █  ▄█▄ █▄█ █ ▀▄█      █ ▀▄ █▄▄█ █▄▄ █▄▄ ▄▄█

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/detection-rules/detection_rules/__main__.py", line 34, in <module>
    main()
  File "/opt/detection-rules/detection_rules/__main__.py", line 31, in main
    root(prog_name="detection_rules")
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/detection-rules/detection_rules/cli_utils.py", line 94, in get_collection
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/detection-rules/detection_rules/kbwrap.py", line 72, in upload_rule
    payload = downgrade(payload, target_version=kibana.version)
  File "/opt/detection-rules/detection_rules/schemas/__init__.py", line 188, in downgrade
    api_contents = migrations[version](version, api_contents)
  File "/opt/detection-rules/detection_rules/schemas/__init__.py", line 166, in migrate_to_7_14
    return strip_additional_properties(version, api_contents)
  File "/opt/detection-rules/detection_rules/schemas/__init__.py", line 67, in strip_additional_properties
    jsonschema.validate(stripped, target_schema)
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: {'id': 'endpoint_list', 'list_id': 'endpoint_list', 'namespace_type': 'agnostic', 'type': 'endpoint'} is not of type 'string'

Failed validating 'type' in schema['properties']['exceptions_list']['items']:
    {'type': 'string'}

On instance['exceptions_list'][0]:
    {'id': 'endpoint_list',
     'list_id': 'endpoint_list',
     'namespace_type': 'agnostic',
     'type': 'endpoint'}
Exception ignored in: <function Kibana.__del__ at 0x7facafc32ee0>
Traceback (most recent call last):
  File "/opt/detection-rules/kibana/connector.py", line 165, in __del__
  File "/opt/detection-rules/kibana/connector.py", line 154, in logout
  File "/opt/detection-rules/kibana/connector.py", line 96, in get
  File "/opt/detection-rules/kibana/connector.py", line 80, in request
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 519, in request
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 444, in prepare_request
  File "/usr/local/lib/python3.8/site-packages/requests/cookies.py", line 544, in merge_cookies
  File "/usr/local/lib/python3.8/site-packages/requests/cookies.py", line 352, in update
  File "/usr/local/lib/python3.8/copy.py", line 92, in copy
ImportError: sys.meta_path is None, Python is likely shutting down
```
The directories that do have a problem (except `ml` that I don't even try as we don't have the license yet) shown to the left with X.
![image](https://user-images.githubusercontent.com/6146328/130438941-09822a6c-2f56-42e7-a19b-c86bc5d26147.png)

**Desktop (please complete the following information):**
 - OS: Debian 10 - Python 3.8
 - Version: ES/Kibana 7.12.1

**Additional context**
The Github Runner shown in the Screenshot and the Desktop get the same error and they both run Python3.8 and point to the same Kibana instance

**Comment by operatorequals** [comment]
I was using `main` to parse and upload rules to a `7.12.1` instance.
It didn't work :)
