### ISSUE TITLE
[Bug] CLI Create Rule Crash

### ISSUE THREAD

**Issue by cgi-gerlando-caldara** [elastic/detection-rules#3096]
**Describe the bug**
CLI create-rule is defect with required fields

**To Reproduce**
python -m detection_rules create-rule test
Rule type (query, saved_query, machine_learning, eql, threshold, threat_match, new_terms): **query**
actions (multi, comma separated): **any value**
Crash of code:
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/densanki/Documents/detection-rules/detection_rules/__main__.py", line 34, in <module>
    main()
  File "/home/densanki/Documents/detection-rules/detection_rules/__main__.py", line 31, in main
    root(prog_name="detection_rules")
  File "/home/densanki/Documents/detection-rules/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/densanki/Documents/detection-rules/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/densanki/Documents/detection-rules/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/densanki/Documents/detection-rules/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/densanki/Documents/detection-rules/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/densanki/Documents/detection-rules/detection_rules/main.py", line 56, in create_rule
    return rule_prompt(path, rule_type=rule_type, required_only=required_only, save=True, **contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/densanki/Documents/detection-rules/detection_rules/cli_utils.py", line 169, in rule_prompt
    result = schema_prompt(name, required=name in required_fields, **options.copy())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: detection_rules.misc.schema_prompt() got multiple values for keyword argument 'required'`

**Expected behavior**
Create Rule should run without exception

**Screenshots**
![image](https://github.com/elastic/detection-rules/assets/107175578/013b7309-6701-4b44-bd7d-5507b8a363c8)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 23.04 / Linux 6.2.0-32-generic

**Comment by Georgios90** [comment]
I am having the same errors my output:
`Rule type (query, saved_query, machine_learning, eql, threshold, threat_match, new_terms): query
actions (multi, comma separated): 
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/gkapoglis/Documents/GitHub/detection-rules/detection_rules/__main__.py", line 34, in <module>
    main()
  File "/Users/gkapoglis/Documents/GitHub/detection-rules/detection_rules/__main__.py", line 31, in main
    root(prog_name="detection_rules")
  File "/Users/gkapoglis/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gkapoglis/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/gkapoglis/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gkapoglis/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gkapoglis/Library/Python/3.9/lib/python/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/gkapoglis/Documents/GitHub/detection-rules/detection_rules/main.py", line 56, in create_rule
    return rule_prompt(path, rule_type=rule_type, required_only=required_only, save=True, **contents)
  File "/Users/gkapoglis/Documents/GitHub/detection-rules/detection_rules/cli_utils.py", line 169, in rule_prompt
    result = schema_prompt(name, required=name in required_fields, **options.copy())
TypeError: detection_rules.misc.schema_prompt() got multiple values for keyword argument 'required'`

**Comment by Georgios90** [comment]
Platform : MacOS

**Comment by Mikaayenson** [comment]
👋 Thanks @cgi-gerlando-caldara for opening the issue! The `alert_suppression` field in the schemas we auto generate includes a sub field `required`, causing the keyword argument `required` to be passed multiple times to the schema_prompt function. We'll open a PR to resolve this.
