### ISSUE TITLE
[Bug] import-rules-to-repo command makes improper reference to rule type

### ISSUE THREAD

**Issue by 0xdeadbeefJERKY** [elastic/detection-rules#4011]
### Describe the Bug

The `import-rules-to-repo` command consistently fails because it attempts to [reference the rule type field from the root level](https://github.com/elastic/detection-rules/blob/main/detection_rules/main.py#L155) rather than as a sub-key within the `[rule]` level.

### To Reproduce

1. Run the `import-rules-to-repo` command against any existing, valid rule. For example:
 
```bash
➜ python -m detection_rules import-rules-to-repo ./rules/windows/defense_evasion_masquerading_as_elastic_endpoint_process.toml

█▀▀▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄   ▄      █▀▀▄ ▄  ▄ ▄   ▄▄▄ ▄▄▄
█  █ █▄▄  █  █▄▄ █    █   █  █ █ █▀▄ █      █▄▄▀ █  █ █   █▄▄ █▄▄
█▄▄▀ █▄▄  █  █▄▄ █▄▄  █  ▄█▄ █▄█ █ ▀▄█      █ ▀▄ █▄▄█ █▄▄ █▄▄ ▄▄█

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/user/detection-engineering/detection-rules/detection_rules/__main__.py", line 35, in <module>
    main()
  File "/home/user/detection-engineering/detection-rules/detection_rules/__main__.py", line 32, in main
    root(prog_name="detection_rules")
  File "/home/user/detection-engineering/detection-rules/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/detection-engineering/detection-rules/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/detection-engineering/detection-rules/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/detection-engineering/detection-rules/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/detection-engineering/detection-rules/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/detection-engineering/detection-rules/detection_rules/main.py", line 155, in import_rules_into_repo
    if contents["type"] not in get_args(definitions.RuleType):
       ~~~~~~~~^^^^^^^^
KeyError: 'type'
```

### Expected Behavior

`import-rules-to-repo` command should execute successfully without error

### Desktop - OS

Windows

### Desktop - Version

11

### Additional Context

`detection_rules` is being run within a WSL2 environment

**Comment by eric-forte-elastic** [comment]
:wave: Hi, @0xdeadbeefJERKY thank you for writing up this issue and creating a PR! For clarification though, this is primarily a typo in the help text for this CLI command, rather than a bug in its implementation. 

The help text states: `Import rules from json, toml, yaml, or Kibana exported rule file(s).`, which is somewhat misleading. While it does support multiple types (json, toml, or yaml), all of these types require the rule to be the format of a Kibana exported rule (in effect a rule that is in the Kibana API format). The toml rule you are specifying has already been imported and is no longer in the Kibana API format, but is in the detection rules native rule format. Running the `import-rules-to-repo` command on this rule is redundant. If you would like that rule in your folder of custom rules, the recommended action is to either move the rule to a folder specified in your custom `_config.yaml` or add the folder the rule where the rule already exists to this file.

I will make a PR soon to update the help text to be more clear. Thanks!
