### ISSUE TITLE
[Bug] Install dependency using make

### ISSUE THREAD

**Issue by programskillforverification** [elastic/detection-rules#4149]
### Describe the Bug

os: macOS Sequoia
python: 3.12.7
setuptools: 75.1.0

Running `make`, in the last step, RELEASE
```
Successfully installed detection_rules-0.1.0
RELEASE: 
./env/detection-rules-build/bin/python -m detection_rules dev build-release --generate-navigator
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/josephzhao/Dev/cyber-security/detection-rules/detection_rules/__init__.py", line 13, in <module>
    from . import (  # noqa: E402
  File "/Users/josephzhao/Dev/cyber-security/detection-rules/detection_rules/custom_rules.py", line 12, in <module>
    from .main import root
  File "/Users/josephzhao/Dev/cyber-security/detection-rules/detection_rules/main.py", line 22, in <module>
    from .action_connector import (TOMLActionConnectorContents,
  File "/Users/josephzhao/Dev/cyber-security/detection-rules/detection_rules/action_connector.py", line 15, in <module>
    from .mixins import MarshmallowDataclassMixin
  File "/Users/josephzhao/Dev/cyber-security/detection-rules/detection_rules/mixins.py", line 15, in <module>
    import marshmallow_jsonschema
  File "/Users/josephzhao/Dev/cyber-security/detection-rules/env/detection-rules-build/lib/python3.12/site-packages/marshmallow_jsonschema/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
make: *** [release] Error 1
```

### To Reproduce

1. Navigate to the latest version of detection-rules directory
2. Run `make`

### Desktop - OS

macOS

### Additional Context

I think this is maybe due to python version or setuptools version.
When I run 
```
python -c "import pkg_resources"
```
It shows 
```
<string>:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```

**Comment by Mikaayenson** [comment]
Related to https://github.com/elastic/detection-rules/issues/4083

**Comment by shashank-elastic** [comment]
Fixed via PR https://github.com/elastic/detection-rules/pull/4160
